name: mAutoPaste
main: in.mDev.MiracleM4n.mAutoPaste.mAutoPaste
load: startup
version: ${m.version}-${build.number}-${p.version}
author: MiracleM4n
website: http://mdev.in/
description: AutoPasteBin onError