name: mAutoPaste
main: com.miraclem4n.mautopaste.mAutoPaste
load: startup
version: ${m.version}-${build.number}-${p.version}
author: MiracleM4n
website: http://mdev.in/
description: AutoPasteBin onError